name: mythos_manager
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.27.1
  cloud_firestore: ^4.15.10
  firebase_auth: ^4.17.9
  hooks_riverpod: ^2.4.10
  google_fonts: ^6.2.1
  flutter_hooks: ^0.20.5
  http: ^1.2.0
  firebase_app_check: ^0.2.1+19

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^5.4.4
  network_image_mock: ^2.1.1
  mocktail: ^1.0.3
  fake_cloud_firestore: ^2.4.8
  firebase_auth_mocks: ^0.13.0

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
